version: "3"

services:
  keycloak:
    build:
      dockerfile: Dockerfile
      context: ./keycloak/
    restart: always
    ports:
      - "9000:8080"
    environment:
      KEYCLOAK_USER: "root"
      KEYCLOAK_PASSWORD: "password"
      PROXY_ADDRESS_FORWARDING: "true"
